import{S as f,V as y,i as l}from"./assets/vendor-949dc6d4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const b="42782608-9283e0435a58714aa19763cda",L="https://pixabay.com/api/";function S(s,t){const o=new URLSearchParams({key:b,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:20}),i=`${L}/?${o}`;return fetch(i).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function v(s){return s.map(t=>{const{webformatURL:o,tags:i,largeImageURL:e,likes:r,views:n,comments:p,downloads:h}=t;return` <li class="gallery-item" data-tilt> 
              <a class="gallery-link" href="${e}">
              <img  
                class="gallery-image"
                src="${o}"
                alt="${i}"
              />
            </a>
              <ul class="property-list">
    <li class="list-property-item"><strong>Likes</strong> <br> ${r}</li>
    <li class="list-property-item"><strong>Views</strong> <br> ${n}</li>
    <li class="list-property-item"><strong>Comments</strong> <br> ${p}</li>
    <li class="list-property-item"><strong>Downloads</strong> <br> ${h}</li>
  </ul>
          </li>`}).join("")}const w={message:"Sorry, there are no images matching  your search query. Please, try again!",messageSize:"16",messageLineHeight:"24",iconUrl:"./img/error.svg",backgroundColor:"rgb(239, 64, 64)",messageColor:"rgb(255, 255, 255)",titleColor:"rgb(255, 255, 255)",position:"topRight",close:"rgb(255, 255, 255)",maxWidth:"432px"},u={iconUrl:"./img/ok.svg",backgroundColor:"rgb(89, 161, 13)",messageColor:"rgb(255, 255, 255)",titleColor:"rgb(255, 255, 255)",position:"topRight",close:"rgb(255, 255, 255)",messageSize:"16",messageLineHeight:"24"},C={message:"You forgot to enter a search query",iconUrl:"./img/warning.svg",backgroundColor:"rgb(255, 160, 0)",messageColor:"rgb(255, 255, 255)",titleColor:"rgb(255, 255, 255)",position:"topRight",close:"rgb(255, 255, 255)",messageSize:"16",messageLineHeight:"24"},q={message:"Welcome! Please enter your search query!",iconUrl:"./img/bell.svg",backgroundColor:"rgb(0, 153, 255)",messageColor:"rgb(255, 255, 255)",titleColor:"rgb(255, 255, 255)",position:"topRight",close:"rgb(255, 255, 255)",messageSize:"16",messageLineHeight:"24"},d=document.querySelector(".js-search-form"),a=d.querySelector(".js-input"),c=document.querySelector(".js-loader"),m=document.querySelector(".js-gallery");let g,$=1;d.addEventListener("submit",E);function E(s){if(s.preventDefault(),c.classList.remove("is-hidden"),m.innerHTML="",g=s.currentTarget.elements["user-search-q"].value.trim(),!g)return P();S(g,$).then(t=>{if(t.hits.length===0)return k();R(t.total),m.innerHTML=v(t.hits),new f(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),y.init(document.querySelectorAll(".gallery-item"),{max:25,speed:400})}).catch(console.log),s.currentTarget.reset()}a.addEventListener("focus",()=>{a.removeAttribute("placeholder")});a.addEventListener("blur",()=>{a.setAttribute("placeholder","Search images...")});l.info(q);function P(){c.classList.add("is-hidden"),l.warning(C)}function k(){c.classList.add("is-hidden"),l.error(w)}function R(s){c.classList.add("is-hidden"),u.message=`We found ${s} photos`,l.success(u)}
//# sourceMappingURL=commonHelpers.js.map
