import{a as b,S as O,V as k,i as u}from"./assets/vendor-fa6f2b3b.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();b.defaults.baseURL="https://pixabay.com/api/";const E="42782608-9283e0435a58714aa19763cda";async function L(e,r,i){const{data:s}=await b.get("",{params:{key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:i}});return s}let R=new O(".gallery a",{captionsData:"alt",captionDelay:250});const f=document.querySelector(".js-gallery");function w(e){f.insertAdjacentHTML("beforeend",j(e)),R.refresh(),k.init(document.querySelectorAll(".gallery-item"),{max:25,speed:400})}function j(e){return e.map(r=>{const{webformatURL:i,tags:s,largeImageURL:t,previewURL:o,likes:a,views:q,comments:P,downloads:$}=r;return` <li class="gallery-item blurred-img" data-tilt> 
              <a class="gallery-link " href="${t}">
              <img  
                class="gallery-image lazyload"
                data-src="${i}"
                src="${o}"
                alt="${s}"
              />
            </a>
              <ul class="property-list">
    <li class="list-property-item"><strong>Likes</strong> <br> ${a}</li>
    <li class="list-property-item"><strong>Views</strong> <br> ${q}</li>
    <li class="list-property-item"><strong>Comments</strong> <br> ${P}</li>
    <li class="list-property-item"><strong>Downloads</strong> <br> ${$}</li>
  </ul>
          </li>`}).join("")}function U(){let r=f.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"})}const x={message:"Sorry, there are no images matching  your search query. Please, try again!",messageSize:"16",messageLineHeight:"24",iconUrl:"./img/error.svg",backgroundColor:"rgb(239, 64, 64)",messageColor:"rgb(255, 255, 255)",titleColor:"rgb(255, 255, 255)",position:"topRight",close:"rgb(255, 255, 255)",maxWidth:"432px"},p={iconUrl:"./img/ok.svg",backgroundColor:"rgb(89, 161, 13)",messageColor:"rgb(255, 255, 255)",titleColor:"rgb(255, 255, 255)",position:"topRight",close:"rgb(255, 255, 255)",messageSize:"16",messageLineHeight:"24"},c={iconUrl:"./img/warning.svg",backgroundColor:"rgb(255, 160, 0)",messageColor:"rgb(255, 255, 255)",titleColor:"rgb(255, 255, 255)",position:"topRight",close:"rgb(255, 255, 255)",messageSize:"16",messageLineHeight:"24"};function z(){c.message="You forgot to enter a search query",u.warning(c)}function A(){u.error(x)}function H(e){p.message=`We found ${e} photos`,u.success(p)}function B(e){c.message=`We're sorry, but you've reached the end of search of ${e} results`,u.warning(c)}const v=document.querySelector(".js-search-form"),g=v.querySelector(".js-input"),S=document.querySelector(".js-loader"),h=document.querySelector(".js-load-more");let l,d=15,n=1,y;v.addEventListener("submit",F);h.addEventListener("click",I);g.addEventListener("focus",()=>{g.removeAttribute("placeholder")});g.addEventListener("blur",()=>{g.setAttribute("placeholder","Search images...")});async function F(e){if(e.preventDefault(),m(),f.innerHTML="",n=1,l=e.currentTarget.elements["user-search-q"].value.trim(),!l)return z();try{C();const r=await L(l,n,d);if(r.hits.length===0)return A();H(r.total),w(r.hits),r.total<d?m():T(),e.target.reset()}catch(r){console.log(r)}finally{M()}}async function I(){n+=1;try{C();const e=await L(l,n,d);w(e.hits),U(),y=Math.ceil(e.total/d),y===n&&(m(),B(e.total))}catch(e){console.log(e)}finally{M()}}function T(){h.classList.remove("is-hidden")}function m(){h.classList.add("is-hidden")}function C(){S.classList.remove("is-hidden")}function M(){S.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
