import{a as y,S as $,V as O,i as u}from"./assets/vendor-1744691a.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();y.defaults.baseURL="https://pixabay.com/api/";const k="42782608-9283e0435a58714aa19763cda";async function b(e,r,i){const{data:s}=await y.get("",{params:{key:k,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:i}});return s}let E=new $(".gallery a",{captionsData:"alt",captionDelay:250});const p=document.querySelector(".js-gallery");function L(e){p.insertAdjacentHTML("beforeend",R(e)),E.refresh(),O.init(document.querySelectorAll(".gallery-item"),{max:25,speed:400})}function R(e){return e.map(r=>{const{webformatURL:i,tags:s,largeImageURL:t,previewURL:o,likes:a,views:M,comments:q,downloads:P}=r;return` <li class="gallery-item blurred-img" data-tilt> 
              <a class="gallery-link " href="${t}">
              <img  
                class="gallery-image lazyload"
                data-src="${i}"
                src="${o}"
                alt="${s}"
              />
            </a>
              <ul class="property-list">
    <li class="list-property-item"><strong>Likes</strong> <br> ${a}</li>
    <li class="list-property-item"><strong>Views</strong> <br> ${M}</li>
    <li class="list-property-item"><strong>Comments</strong> <br> ${q}</li>
    <li class="list-property-item"><strong>Downloads</strong> <br> ${P}</li>
  </ul>
          </li>`}).join("")}function j(){let r=p.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"})}const U={message:"Sorry, there are no images matching  your search query. Please, try again!",messageSize:"16",messageLineHeight:"24",iconUrl:"./img/error.svg",backgroundColor:"rgb(239, 64, 64)",messageColor:"rgb(255, 255, 255)",titleColor:"rgb(255, 255, 255)",position:"topRight",close:"rgb(255, 255, 255)",maxWidth:"432px"},c={iconUrl:"./img/ok.svg",backgroundColor:"rgb(89, 161, 13)",messageColor:"rgb(255, 255, 255)",titleColor:"rgb(255, 255, 255)",position:"topRight",close:"rgb(255, 255, 255)",messageSize:"16",messageLineHeight:"24"},x={message:"You forgot to enter a search query",iconUrl:"./img/warning.svg",backgroundColor:"rgb(255, 160, 0)",messageColor:"rgb(255, 255, 255)",titleColor:"rgb(255, 255, 255)",position:"topRight",close:"rgb(255, 255, 255)",messageSize:"16",messageLineHeight:"24"},w=document.querySelector(".js-search-form"),g=w.querySelector(".js-input"),v=document.querySelector(".js-loader"),f=document.querySelector(".js-load-more");let l,d=15,n=1,h;w.addEventListener("submit",z);f.addEventListener("click",A);g.addEventListener("focus",()=>{g.removeAttribute("placeholder")});g.addEventListener("blur",()=>{g.setAttribute("placeholder","Search images...")});async function z(e){if(e.preventDefault(),m(),p.innerHTML="",n=1,l=e.currentTarget.elements["user-search-q"].value.trim(),!l)return I();try{S();const r=await b(l,n,d);if(r.hits.length===0)return B();F(r.total),L(r.hits),r.total<d?m():H(),e.target.reset()}catch(r){console.log(r)}finally{C()}}async function A(){n+=1;try{S();const e=await b(l,n,d);L(e.hits),j(),h=Math.ceil(e.total/d),h===n&&(m(),T(e.total))}catch(e){console.log(e)}finally{C()}}function H(){f.classList.remove("is-hidden")}function m(){f.classList.add("is-hidden")}function I(){u.warning(x)}function B(){u.error(U)}function F(e){c.message=`We found ${e} photos`,u.success(c)}function T(e){c.message=`It's all ${e} photos`,u.success(c)}function S(){v.classList.remove("is-hidden")}function C(){v.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
